a_min_max: false
a_sym: false
act_bit: 8
base:
- models/ldm/lsun_churches256\config.yaml
batch_size: 20
cali_batch_size: 32
cali_ckpt: C:\Users\wsh\Desktop\q-diffusion-master\church_w4a8_ckpt.pth
cali_data_path: sd_coco_sample1024_allst.pt
cali_iters: 20000
cali_iters_a: 5000
cali_lr: 0.0004
cali_n: 1024
cali_p: 2.4
cali_st: 1
cond: false
custom_steps: 400
dpm: false
eta: 0.0
init_debug_log: false
init_log_interval: 50
logdir: church_w8a8_sample
n_samples: 2000
ptq: true
quant_act: true
quant_mode: qdiff
resume: true
resume_base: models/ldm/lsun_churches256/model.ckpt
resume_w: false
rs_sm_only: false
running_stat: false
seed: 41
sm_abit: 8
vanilla_sample: false
verbose: false
weight_bit: 4
